name: Static Analysis

on:
  push:
    branches:
      - main
      - development
      - '*.x'
  pull_request:

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction --no-progress

      - name: Check code style
        run: composer check-style || true

      - name: Run tests
        run: composer test || true
